### ISSUE TITLE
font dropshadow still shows while alpha is 0

### ISSUE THREAD

**Issue by ritalinaddict** [kwilcz/Antario#71]
thought I should tell you that the font's drop shadow (when using the flag) will still show even though the fonts alpha is set to 0 (seems to be because the dropshadow doesn't take into account your fonts alpha). also you should probably add a flag for outlining text (i think ive seen it in a few older d3dfont classes) as drawing white text over any light color is almost unreadable no matter what weight/font you use

[also on a random note in drawmanager you only set tahoma10 to nullptr](https://github.com/Wando1423/Antario/blob/master/Antario/Utils/DrawManager.cpp#L14)

**Comment by certmemer** [comment]
fixed bro

**Comment by ritalinaddict** [comment]
whoops you forgot to also fix it for [DrawString](https://github.com/Wando1423/Antario/blob/master/Antario/Utils/D3DFont.cpp#L615), you only did it for DrawStringScaled. also the color you set the shadow to (dwColor & 0x00ffffff) seems way too bright. changing it to 0x9a000000 (color you used before) instead of 0x00ffffff makes it look normal again.
  
apart from those hotfix's it works perfectly, thank you (wasnt sure if I should make a new issue or not, didnt want to clutter up the github)

**Comment by certmemer** [comment]
yea i made the shadow get the original color of the text and that messed it up lol, it's fine now
